#!/usr/bin/env python3
"""
scripts/governor_harness/revalidate_under_performance.py

Re-runs every latency-bearing measurement script under a taskset-pinned,
performance-governor, turbo-disabled environment, and preserves both the
old (powersave) and new (performance) artifacts so they can be diffed by
diff_revalidation.py.

This script does NOT fabricate or estimate anything: it refuses to run
unless the live cpufreq governor actually reads "performance" (see
setup_performance_governor.sh), and every number it produces comes from
actually executing the named script.

Usage:
    sudo ./scripts/governor_harness/setup_performance_governor.sh
    python3 scripts/governor_harness/revalidate_under_performance.py
    python3 scripts/governor_harness/revalidate_under_performance.py --cpus 2,3
    python3 scripts/governor_harness/revalidate_under_performance.py --only comparison,throughput
    sudo ./scripts/governor_harness/setup_performance_governor.sh --restore
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
ARTIFACTS = REPO_ROOT / "artifacts"
REVAL_DIR = ARTIFACTS / "performance_revalidation"
BASELINE_DIR = REVAL_DIR / "baseline_powersave"
PERFORMANCE_DIR = REVAL_DIR / "performance"

# (key, script relative path, output artifact relative path)
# Order matters: scripts that derive from another script's output run after it.
TARGETS = [
    ("comparison", "tests/benchmark_comparison.py", "artifacts/comparison_results.json"),
    ("throughput", "tests/benchmark_throughput.py", "artifacts/throughput_results.json"),
    ("rotation_strategy", "scripts/rotation_strategy_comparison.py", "artifacts/rotation_strategy_comparison.json"),
    ("amortization", "scripts/generate_amortization_table.py", "artifacts/amortization_table.json"),
    ("matched_pair", "scripts/privacy_cost_matched_pair.py", "artifacts/privacy_cost_matched_pair.json"),
    ("privacy_cost", "scripts/privacy_cost_analysis.py", "artifacts/privacy_cost_analysis.json"),
    ("ablation", "scripts/generate_ablation.py", "results/ablation_methodology.json"),
    ("execution_matrix", "scripts/build_execution_matrix.py", "artifacts/execution_matrix.json"),
    ("e2e_breakdown", "scripts/e2e_latency_breakdown.py", "artifacts/e2e_latency_breakdown.json"),
    ("bandwidth_ladder", "scripts/bandwidth_ladder.py", "artifacts/bandwidth_ladder.json"),
    ("hhe_breakeven", "scripts/hhe_breakeven.py", "artifacts/hhe_breakeven.json"),
]

TRANSCIPHERING_DIR = REPO_ROOT / "tools" / "transciphering"
HERA_LANES = [1, 4, 8, 16]
HERA_EXISTING_RESULTS = [
    TRANSCIPHERING_DIR / "results" / f"hera_bench_lane{n}.json" for n in HERA_LANES
]


def _read_governor() -> str:
    govs = set()
    for p in Path("/sys/devices/system/cpu").glob("cpu[0-9]*/cpufreq/scaling_governor"):
        govs.add(p.read_text().strip())
    if len(govs) != 1:
        return f"MIXED:{sorted(govs)}"
    return govs.pop()


def _read_turbo_disabled() -> bool | str:
    no_turbo = Path("/sys/devices/system/cpu/intel_pstate/no_turbo")
    boost = Path("/sys/devices/system/cpu/cpufreq/boost")
    if no_turbo.exists():
        return no_turbo.read_text().strip() == "1"
    if boost.exists():
        return boost.read_text().strip() == "0"
    return "UNKNOWN (no intel_pstate/no_turbo or cpufreq/boost file found)"


# Snapshot directory name -> the cpu_governor value every file inside it
# must be stamped with. This is the single source of truth the consistency
# guard (here and in c3_client_server_comparison.py) checks against.
SNAPSHOT_EXPECTED_GOVERNOR = {
    "baseline_powersave": "powersave",
    "performance": "performance",
}


def _write_manifest_sidecar(dst: Path, manifest: dict) -> None:
    sidecar = dst.parent / f"{dst.stem}.governor_manifest.json"
    sidecar.write_text(json.dumps(manifest, indent=2))


def _snapshot_one(src: Path, snapshot_label: str) -> None:
    if not src.exists():
        print(f"  [baseline] WARNING: {src.relative_to(REPO_ROOT)} does not exist yet, nothing to snapshot")
        return
    dst = BASELINE_DIR / src.name
    if dst.exists():
        print(f"  [baseline] {dst.relative_to(REPO_ROOT)} already snapshotted, not overwriting")
        return
    shutil.copy2(src, dst)
    _write_manifest_sidecar(dst, {
        "cpu_governor": SNAPSHOT_EXPECTED_GOVERNOR[snapshot_label],
        "source": "pre-existing artifact, snapshotted not regenerated by this harness invocation",
        "snapshotted_from": str(src.relative_to(REPO_ROOT)),
        "snapshotted_at_utc": datetime.now(timezone.utc).isoformat(),
    })
    print(f"  [baseline] snapshotted {src.relative_to(REPO_ROOT)} -> {dst.relative_to(REPO_ROOT)} "
          f"(manifest: cpu_governor={SNAPSHOT_EXPECTED_GOVERNOR[snapshot_label]})")


def _snapshot_baseline() -> None:
    BASELINE_DIR.mkdir(parents=True, exist_ok=True)
    for _key, _script, artifact_rel in TARGETS:
        _snapshot_one(REPO_ROOT / artifact_rel, "baseline_powersave")
    for src in HERA_EXISTING_RESULTS:
        _snapshot_one(src, "baseline_powersave")


def _live_manifest_fields(static_fields: dict) -> dict:
    """Re-reads governor/turbo from /sys right now, at the moment a manifest
    is about to be written -- NOT the value cached from the pre-run gate.
    This is what makes the manifest an observation of write-time conditions
    rather than a restatement of the snapshot-label convention."""
    return {
        **static_fields,
        "cpu_governor": _read_governor(),
        "turbo_disabled": _read_turbo_disabled(),
        "stamped_at_utc": datetime.now(timezone.utc).isoformat(),
    }


def _run_one(key: str, script_rel: str, artifact_rel: str, cpus: str | None, static_fields: dict) -> bool:
    script_path = REPO_ROOT / script_rel
    cmd = [sys.executable, str(script_path)]
    if cpus:
        cmd = ["taskset", "-c", cpus] + cmd
    print(f"\n[{key}] $ {' '.join(cmd)}")
    t0 = time.time()
    result = subprocess.run(cmd, cwd=str(REPO_ROOT))
    wall_s = time.time() - t0
    if result.returncode != 0:
        print(f"[{key}] FAILED (exit {result.returncode}), wall={wall_s:.1f}s")
        return False

    artifact_path = REPO_ROOT / artifact_rel
    if not artifact_path.exists():
        print(f"[{key}] FAILED: expected output {artifact_rel} not found")
        return False

    PERFORMANCE_DIR.mkdir(parents=True, exist_ok=True)
    dst = PERFORMANCE_DIR / artifact_path.name
    shutil.copy2(artifact_path, dst)

    live = _live_manifest_fields(static_fields)
    manifest_path = PERFORMANCE_DIR / f"{artifact_path.stem}.governor_manifest.json"
    manifest_path.write_text(json.dumps({**live, "wall_seconds": round(wall_s, 1)}, indent=2))
    print(f"[{key}] OK, wall={wall_s:.1f}s, cpu_governor(at write)={live['cpu_governor']} "
          f"-> {dst.relative_to(REPO_ROOT)}")
    return True


def _run_hera_benches(cpus: str | None, static_fields: dict) -> bool:
    if shutil.which("go") is None:
        print("\n[hera_bench] SKIPPED: 'go' not found on PATH, leaving existing "
              "tools/transciphering/results/hera_bench_lane*.json untouched for this run.")
        return True
    ok = True
    PERFORMANCE_DIR.mkdir(parents=True, exist_ok=True)
    for lanes in HERA_LANES:
        cmd = ["go", "run", "./bench", "--features=256", f"--lanes={lanes}", "--rounds=100"]
        if cpus:
            cmd = ["taskset", "-c", cpus] + cmd
        print(f"\n[hera_bench lanes={lanes}] $ {' '.join(cmd)}  (cwd={TRANSCIPHERING_DIR.relative_to(REPO_ROOT)})")
        t0 = time.time()
        result = subprocess.run(cmd, cwd=str(TRANSCIPHERING_DIR))
        wall_s = time.time() - t0
        if result.returncode != 0:
            print(f"[hera_bench lanes={lanes}] FAILED (exit {result.returncode})")
            ok = False
            continue
        produced = TRANSCIPHERING_DIR / "results" / "hera_bench.json"
        if not produced.exists():
            print(f"[hera_bench lanes={lanes}] FAILED: {produced} not written")
            ok = False
            continue
        dst = PERFORMANCE_DIR / f"hera_bench_lane{lanes}.json"
        shutil.copy2(produced, dst)
        live = _live_manifest_fields(static_fields)
        manifest_path = PERFORMANCE_DIR / f"hera_bench_lane{lanes}.governor_manifest.json"
        manifest_path.write_text(json.dumps({**live, "wall_seconds": round(wall_s, 1)}, indent=2))
        print(f"[hera_bench lanes={lanes}] OK, wall={wall_s:.1f}s, cpu_governor(at write)={live['cpu_governor']} "
              f"-> {dst.relative_to(REPO_ROOT)}")
    return ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cpus", default=None,
                        help="taskset CPU list to pin every subprocess to, e.g. '2,3'. "
                             "Omit to run unpinned (not recommended for the final run).")
    parser.add_argument("--only", default=None,
                        help="comma-separated subset of target keys to run "
                             f"(available: {','.join(k for k, _, _ in TARGETS)}, hera_bench)")
    parser.add_argument("--allow-non-performance", action="store_true",
                        help="Skip the governor=performance hard gate. For testing this "
                             "harness's plumbing only -- any numbers produced this way are "
                             "NOT valid for the paper and must not be cited.")
    args = parser.parse_args()

    governor = _read_governor()
    turbo_disabled = _read_turbo_disabled()
    print(f"cpu_governor = {governor}")
    print(f"turbo_disabled = {turbo_disabled}")

    if governor != "performance" and not args.allow_non_performance:
        print(
            "\nERROR: governor is not 'performance' on all cores.\n"
            "Run: sudo ./scripts/governor_harness/setup_performance_governor.sh\n"
            "then re-invoke this script. Refusing to produce numbers that would be "
            "mislabeled -- this mirrors the project's 'no number unless executed under "
            "the stated conditions' rule.",
            file=sys.stderr,
        )
        return 1

    if not args.cpus:
        print(
            "\nWARNING: no --cpus given -- subprocesses will not be taskset-pinned. "
            "RESEARCH_FINDINGS.md Block D1 treats core pinning as close to mandatory "
            "for these sub-millisecond/low-single-digit-ms measurements. Proceeding "
            "anyway, but this run should not be treated as the final validated one.",
        )

    all_keys = {k for k, _, _ in TARGETS} | {"hera_bench"}
    selected = TARGETS
    run_hera = True
    if args.only:
        wanted = set(args.only.split(","))
        unknown = wanted - all_keys
        if unknown:
            print(f"ERROR: unknown target key(s): {sorted(unknown)}", file=sys.stderr)
            return 1
        selected = [t for t in TARGETS if t[0] in wanted]
        run_hera = "hera_bench" in wanted

    print("\nSnapshotting current (pre-run) artifacts as the powersave baseline...")
    _snapshot_baseline()

    # Static, run-level context carried into every manifest. Deliberately does
    # NOT include cpu_governor/turbo_disabled -- those are re-read live at
    # each file's write time by _live_manifest_fields(), not cached here.
    # governor_at_run_start is kept only as a diagnostic breadcrumb, never as
    # the value a manifest asserts -- see the post-run drift check below.
    static_fields = {
        "governor_at_run_start": governor,
        "taskset_cpus": args.cpus,
        "run_started_at_utc": datetime.now(timezone.utc).isoformat(),
        "allow_non_performance_override": args.allow_non_performance,
    }

    failures = []
    for key, script_rel, artifact_rel in selected:
        ok = _run_one(key, script_rel, artifact_rel, args.cpus, static_fields)
        if not ok:
            failures.append(key)

    if run_hera:
        if not _run_hera_benches(args.cpus, static_fields):
            failures.append("hera_bench")

    # Post-run drift check: re-read the governor now that the LAST script has
    # finished. A thermal-throttle or power-profile override mid-run can flip
    # the governor back without any single step failing -- per-file stamps
    # would each look locally fine while the run as a whole drifted. This is
    # the check that catches that case; it is independent of (and in addition
    # to) the per-file live stamps above.
    governor_at_end = _read_governor()
    print(f"\ncpu_governor at run end = {governor_at_end} (was {governor} at run start)")
    drifted = governor_at_end != "performance" and not args.allow_non_performance

    print("\n" + "=" * 70)
    if failures:
        print(f"DONE WITH FAILURES: {failures}")
        print(f"Successful outputs are still in {PERFORMANCE_DIR.relative_to(REPO_ROOT)}/")
        return 1

    if drifted:
        invalid_marker = PERFORMANCE_DIR / "RUN_INVALID_governor_drift.json"
        invalid_marker.write_text(json.dumps({
            "invalid": True,
            "reason": "cpu_governor no longer 'performance' after the run completed -- "
                      "likely thermal throttle or a power-profile override mid-run.",
            "governor_at_run_start": governor,
            "governor_at_run_end": governor_at_end,
            "run_started_at_utc": static_fields["run_started_at_utc"],
            "checked_at_utc": datetime.now(timezone.utc).isoformat(),
        }, indent=2))
        print(
            "RESULT: INVALID -- governor drifted mid-run.\n"
            f"  start: performance -> end: {governor_at_end}\n"
            f"Every artifact just written to {PERFORMANCE_DIR.relative_to(REPO_ROOT)}/ is "
            "UNTRUSTED, even though each individual step reported success.\n"
            f"A marker has been written: {invalid_marker.relative_to(REPO_ROOT)}\n"
            "Fix the cause (reapply the performance governor, check for thermal "
            "throttling / power-profile daemons overriding it) and re-run the full "
            "batch -- do not cherry-pick which files to trust from this run.",
            file=sys.stderr,
        )
        return 1

    print(f"All {len(selected)} targets re-measured under governor=performance "
          f"(verified at run start AND run end).")
    print(f"Baseline (powersave):  {BASELINE_DIR.relative_to(REPO_ROOT)}/")
    print(f"New (performance):     {PERFORMANCE_DIR.relative_to(REPO_ROOT)}/")
    print("Next: python3 scripts/governor_harness/diff_revalidation.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
