package cipher

import "testing"

// TestHERAKnownAnswer is Gate A: it compares this module's keystream against
// ckks_fv's own plainHera reference (RtF_bench_test.go:500-613) for a fixed
// (key, nonce) pair, at the pinned SHA
// 105fc73115b56f1d6ff357029c7682b19a6d8510. No HERA timing number is
// meaningful until this passes.
//
// Vector generated by running the reference function directly (a temporary,
// uncommitted scratch test added to the vendored third_party/ checkout --
// third_party/ is gitignored, so nothing was staged into this repo):
//
//	heraKey[i]   = 1000+i, i = 0..15
//	heraNonce[i] = 2000+i, i = 0..15
//	nonceBytes   = packElems(heraNonce)  // 4 little-endian bytes per element
//	plainHera(5, nonceBytes, heraKey, 1<<26)
//
// -> [25659216 62785430 61075836 56672174 55041421 6788142 25451291 34234690
//     6798004 35538661 55398152 12001395 42711758 31894937 47448404 43070509]
func TestHERAKnownAnswer(t *testing.T) {
	key := make([]uint64, HeraStateSize)
	nonce := make([]uint64, heraNonceElems)
	for i := 0; i < HeraStateSize; i++ {
		key[i] = uint64(1000 + i)
	}
	for i := 0; i < heraNonceElems; i++ {
		nonce[i] = uint64(2000 + i)
	}

	want := [HeraStateSize]uint64{
		25659216, 62785430, 61075836, 56672174, 55041421, 6788142, 25451291, 34234690,
		6798004, 35538661, 55398152, 12001395, 42711758, 31894937, 47448404, 43070509,
	}

	h := HERA16{}
	got := h.encryptBlock(key, nonce, 0)

	if got != want {
		t.Fatalf("HERA keystream block 0 mismatch (does not match ckks_fv's plainHera):\n got  %v\n want %v", got, want)
	}
}

// TestHERAEvalKeyExpansionMatchesEncrypt checks that EvalKeyExpansion returns
// the same round keys Encrypt uses for block 0 (both derive from
// SHAKE256(nonce) via roundKeys).
func TestHERAEvalKeyExpansionMatchesEncrypt(t *testing.T) {
	key := make([]uint64, HeraStateSize)
	nonce := make([]uint64, heraNonceElems)
	for i := 0; i < HeraStateSize; i++ {
		key[i] = uint64(1000 + i)
	}
	for i := 0; i < heraNonceElems; i++ {
		nonce[i] = uint64(2000 + i)
	}

	h := HERA16{}
	rks, err := h.EvalKeyExpansion(key, nonce, nil)
	if err != nil {
		t.Fatalf("EvalKeyExpansion: %v", err)
	}
	if len(rks) != HeraRounds+1 {
		t.Fatalf("want %d round-key rows, got %d", HeraRounds+1, len(rks))
	}

	xof := newShake256()
	xof.Write(packElems(nonce))
	want := roundKeys(xof, HeraRounds, HeraStateSize, key, HeraModulus)
	for r := range want {
		for i := range want[r] {
			if rks[r][i] != want[r][i] {
				t.Fatalf("round %d elem %d: got %d want %d", r, i, rks[r][i], want[r][i])
			}
		}
	}
}
