package cipher

import "testing"

// TestRubatoKnownAnswer is Gate A for Rubato: it compares this module's
// noise-free (sigma=0) keystream against ckks_fv's own plainRubato reference
// (RtF_bench_test.go:615-667) for a fixed (key, nonce, counter) triple, at
// the pinned SHA 105fc73115b56f1d6ff357029c7682b19a6d8510. sigma=0 is used
// because plainRubato's Gaussian noise step draws from a freshly-seeded PRNG
// each call and is non-deterministic run-to-run by design -- see rubato.go's
// package doc comment. No Rubato timing number is meaningful until this
// passes.
//
// Vector generated by running the reference function directly (a temporary,
// uncommitted scratch test added to the vendored third_party/ checkout --
// third_party/ is gitignored, so nothing was staged into this repo):
//
//	rubKey[i]    = 1000+i, i = 0..63
//	rubNonce[i]  = 2000+i, i = 0..15
//	nonceBytes   = packElems(rubNonce)  // 4 little-endian bytes per element
//	counter0     = 8 zero bytes (block 0)
//	plainRubato(64, 2, nonceBytes, counter0, rubKey, 0x1fc0001, sigma=0)
//
// -> [3343014 23307946 10712087 15989743 31870248 18658134 9979031 24144196
//     22739492 14468275 30200372 32959726 9552511 23846846 9847143 26118512
//     26244790 8686360 22061231 31310280 11846825 30901102 13368665 20218379
//     26885671 24826431 709250 21962635 22733357 8495490 20893271 14889478
//     31967363 27562833 18236288 2110505 9690954 10096024 24039763 25116944
//     12494659 4495686 5656527 5782420 4600901 19838190 11049708 22688928
//     24445745 26126276 343091 30969558 5610880 15115947 28911217 16593876
//     2677921 11452401 20731042 13760287]  (60 elements)
func TestRubatoKnownAnswer(t *testing.T) {
	key := make([]uint64, RubatoBlockSize)
	nonce := make([]uint64, rubatoNonceElems)
	for i := 0; i < RubatoBlockSize; i++ {
		key[i] = uint64(1000 + i)
	}
	for i := 0; i < rubatoNonceElems; i++ {
		nonce[i] = uint64(2000 + i)
	}

	want := [RubatoOutputSize]uint64{
		3343014, 23307946, 10712087, 15989743, 31870248, 18658134, 9979031, 24144196,
		22739492, 14468275, 30200372, 32959726, 9552511, 23846846, 9847143, 26118512,
		26244790, 8686360, 22061231, 31310280, 11846825, 30901102, 13368665, 20218379,
		26885671, 24826431, 709250, 21962635, 22733357, 8495490, 20893271, 14889478,
		31967363, 27562833, 18236288, 2110505, 9690954, 10096024, 24039763, 25116944,
		12494659, 4495686, 5656527, 5782420, 4600901, 19838190, 11049708, 22688928,
		24445745, 26126276, 343091, 30969558, 5610880, 15115947, 28911217, 16593876,
		2677921, 11452401, 20731042, 13760287,
	}

	r := Rubato128L{}
	got := r.encryptBlock(key, nonce, 0, 0) // sigma=0: deterministic algebra only

	if got != want {
		t.Fatalf("Rubato128L keystream block 0 mismatch (does not match ckks_fv's plainRubato):\n got  %v\n want %v", got, want)
	}
}

// TestRubatoNoiseBounded checks the AGN step is present (Encrypt's real
// sigma=RubatoSigma path differs from the sigma=0 path) and that individual
// noise draws stay within the reference's bound = 6*sigma
// (rubatoAddGaussianNoise, RtF_bench_test.go:766-769). Not a bit-exact check
// -- the noise is randomized by design.
func TestRubatoNoiseBounded(t *testing.T) {
	key := make([]uint64, RubatoBlockSize)
	nonce := make([]uint64, rubatoNonceElems)
	for i := 0; i < RubatoBlockSize; i++ {
		key[i] = uint64(1000 + i)
	}
	for i := 0; i < rubatoNonceElems; i++ {
		nonce[i] = uint64(2000 + i)
	}

	r := Rubato128L{}
	noiseFree := r.encryptBlock(key, nonce, 0, 0)
	sigma := float64(RubatoSigma)
	bound := int64(6 * sigma)

	for trial := 0; trial < 20; trial++ {
		noisy := r.encryptBlock(key, nonce, 0, RubatoSigma)
		diffSeen := false
		for i := range noisy {
			d := int64(noisy[i]) - int64(noiseFree[i])
			// Handle mod-q wraparound in either direction.
			if d > int64(RubatoModulus)/2 {
				d -= int64(RubatoModulus)
			} else if d < -int64(RubatoModulus)/2 {
				d += int64(RubatoModulus)
			}
			if d != 0 {
				diffSeen = true
			}
			if d > bound || d < -bound {
				t.Fatalf("trial %d elem %d: noise delta %d exceeds bound %d", trial, i, d, bound)
			}
		}
		if !diffSeen {
			t.Fatalf("trial %d: sigma=%v produced no difference from sigma=0 (AGN step missing?)", trial, RubatoSigma)
		}
	}
}
